// src/config/providers.ts — Provider bootstrap
// Auto-generated by DoNotDev scaffolding. Edit freely.
// When you add a backend (Firebase, Supabase), replace this file with the appropriate provider setup.
// See: guides/dndev/SETUP_PROVIDERS.md

// No backend configured — nothing to register.
// To add a backend later, run: dndev create-app (in an existing project, it merges)
