// Generated by @donotdev/config - DO NOT EDIT
// This file will be regenerated when src/pages changes
// To customize: edit src/pages/legal/PrivacyPage.tsx or create manual app/** files

import PrivacyPage from '../../../pages/legal/PrivacyPage';

export const metadata = {
  "namespace": "privacy",
  "icon": "Shield",
  "hideFromMenu": true
};

export default PrivacyPage;
