// Generated by @donotdev/config - DO NOT EDIT
// This file will be regenerated when src/pages changes
// To customize: edit src/pages/HomePage.tsx or create manual app/** files
'use client';

import HomePage from '../pages/HomePage';

export default HomePage;
