// Generated by @donotdev/config - DO NOT EDIT
// This file will be regenerated when src/pages changes
// To customize: edit src/pages/legal/LegalNoticePage.tsx or create manual app/** files

import LegalNoticePage from '../../../pages/legal/LegalNoticePage';

export const metadata = {
  "namespace": "legalNotice",
  "icon": "Building",
  "hideFromMenu": true
};

export default LegalNoticePage;
