// Generated by @donotdev/config - DO NOT EDIT
// This file will be regenerated when src/pages changes
// To customize: edit src/pages/legal/TermsPage.tsx or create manual app/** files

import TermsPage from '../../../pages/legal/TermsPage';

export const metadata = {
  "namespace": "terms",
  "icon": "FileText",
  "hideFromMenu": true
};

export default TermsPage;
